GET http://localhost:8080/currency
GET http://localhost:8080/currency/EUR
GET http://localhost:8080/exchangeRates
GET http://localhost:8080/exchangeRate/EURUSD
POST http://localhost:8080/exchangeRates?id1=2&id2=4&rate=1,09
POST http://localhost:8080/currency_add?code=USD&fullname=United%20States%20dollar&sign=$
PATCH http://localhost:8080/exchangeRates/EURUSD?rate=1,11
